### ISSUE TITLE
`flat_set.insert(first, last)` cannot possibly happen in linear time

### ISSUE THREAD

**Issue by Quuxplusone** [tzlaine/flat_map#11]
>     template <class InputIterator>
>     void insert(sorted_unique_t, InputIterator first, InputIterator last);
> Expects: The range `[first,last)` is sorted with respect to `value_comp()`.
> Effects: Equivalent to: `insert(first, last)`.
> Complexity: Linear.

Consider

    flat_set<CaseInsensitiveString> s = {"a", "c", "e", "g", "i", "k"};
    CaseInsensitiveString arr[5] = {"A", "B", "E", "F", "I", "J"};
    s.insert(sorted_unique, arr, arr+5);

I can think of only two ways to implement the `insert`.

One, we could find the insertion point for A and insert it to produce Acegik, then find the insertion point for B (which we know must be to the right of A) and insert it to produce ABcegik, then find the insertion point for C... and so on. This requires O(n) insertions, which means it's order `n^2` in general.

Two, we could append ABEFIJ to the end of the container (order `n`), stable-sort it to produce aABceEFgiIJk (order `n log n`), and then unique it (order `n`) to produce ABcEFgIJk. This is order `n log n` in general.

So I don't think it's possible to do it in "Linear" time.

Separately, note that if insertion into the underlying container — or sorting the underlying container — ever throws an exception, then we have no idea what is the state of the underlying container, which means we may have broken our "always-sorted-and-uniqued" invariant. If `sort` ever throws, we basically have to `clear` the entire container, if we want to preserve our invariant.

**Comment by Quuxplusone** [comment]
Three, we could walk through the underlying container and the insertion-list in parallel, performing a "set intersection" kind of operation. Each time we find an element already in the set we replace it; each time we don't find an element we append it. So in order `n` time we produce AcEgIkBFJ, and then we sort it (order `n log n`) to produce ABcEFgIJk. This is order `n log n` in general, and never allocates more memory than we need, so it's probably best.

...oops, except `insert(first, last)` is supposed to *preserve* existing elements, not replace them! So all my examples are wrong, but the big-Os are still correct AFAIK.

**Comment by dimztimz** [comment]
The function `void insert(sorted_unique_t, InputIterator first, InputIterator last)` is a union operation on two sets, both represented as sorted ranges. The classic [set_union](https://en.cppreference.com/w/cpp/algorithm/set_union) would do, provided that extra allocation is done for the output range. See Wikipedia for more [general overview](https://en.wikipedia.org/wiki/Merge_algorithm). This algorithm has linear time complexity.

The question is, do we want that extra allocation? I am thinking on an optimization when `size(a) + size(b) <= capacity(a)`, one can avoid that allocation.

This proposal raises more questions that is provides answers. I am amazed it how far it got without having actual implementation, which should answer many of the questions.
